package gentle

import "github.com/stretchr/testify/mock"

// Generated by github.com/vektra/mockery

type mockBackOffFactory struct {
	*mock.Mock
}

func NewMockBackOffFactory(mock *mock.Mock) *mockBackOffFactory {
	return &mockBackOffFactory{
		Mock: mock,
	}
}

// NewBackOff provides a mock function with given fields:
func (_m *mockBackOffFactory) NewBackOff() BackOff {
	ret := _m.Called()

	var r0 BackOff
	if rf, ok := ret.Get(0).(func() BackOff); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(BackOff)
	}

	return r0
}
