package gentle

import "github.com/stretchr/testify/mock"

// Generated by github.com/vektra/mockery

// MockStream mocks Stream interface
type MockStream struct {
	mock.Mock
}

// Get provides a mock function with given fields:
func (_m *MockStream) Get() (Message, error) {
	ret := _m.Called()

	var r0 Message
	if rf, ok := ret.Get(0).(func() Message); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(Message)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
