package gentle

import "github.com/stretchr/testify/mock"

// Generated by github.com/vektra/mockery

type mockHandler struct {
	*mock.Mock
}

func NewMockHandler(mock *mock.Mock) *mockHandler {
	return &mockHandler{
		Mock: mock,
	}
}

// Handle provides a mock function with given fields: msg
func (_m *mockHandler) Handle(msg Message) (Message, error) {
	ret := _m.Called(msg)

	var r0 Message
	if rf, ok := ret.Get(0).(func(Message) Message); ok {
		r0 = rf(msg)
	} else {
		r0 = ret.Get(0).(Message)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(Message) error); ok {
		r1 = rf(msg)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
