package gentle

import "github.com/stretchr/testify/mock"

import "time"

// Generated by github.com/vektra/mockery

type mockBackOff struct {
	*mock.Mock
}

func NewMockBackOff(mock *mock.Mock) *mockBackOff {
	return &mockBackOff{
		Mock: mock,
	}
}

// Next provides a mock function with given fields:
func (_m *mockBackOff) Next() time.Duration {
	ret := _m.Called()

	var r0 time.Duration
	if rf, ok := ret.Get(0).(func() time.Duration); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(time.Duration)
	}

	return r0
}
